<?php

return [
    App\Providers\AccountServiceProvider::class,
    App\Providers\AddressServiceProvider::class,
    App\Providers\AdsServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\CategoryServiceProvider::class,
    App\Providers\ChatListServiceProvider::class,
    App\Providers\ChatServiceProvider::class,
    App\Providers\CustomerServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\GetAdsServiceProvider::class,
    App\Providers\OrderProvider::class,
    App\Providers\OrderServiceProvider::class,
    App\Providers\PermissionServiceProvider::class,
    App\Providers\ProductServiceProvider::class,
    App\Providers\RoleServiceProvider::class,
    App\Providers\ShopCustomerServiceProvider::class,
    App\Providers\ShopOrderServiceProvider::class,
    App\Providers\ShopProductProvider::class,
    App\Providers\ShopServiceProvider::class,
    App\Providers\SocialNetworkServiceProvider::class,
    App\Providers\UserServiceProvider::class,
];
